package tech.grimm.wintermute.utils

enum class Currency(val description: String) {
    AUD("Australia Dollar"),
    CAD("Canada Dollar"),
    CHF("Switzerland Franc"),
    DKK("Denmark Krone"),
    EUR("Euro Member Countries"),
    GBP("United Kingdom Pound"),
    HKD("Hong Kong Dollar"),
    IDR("Indonesia Rupiah"),
    ILS("Israel Shekel"),
    INR("India Rupee"),
    ISK("Iceland Krona"),
    JEP("Jersey Pound"),
    JPY("Japan Yen"),
    KPW("Korea (North) Won"),
    KRW("Korea (South) Won"),
    MXN("Mexico Peso"),
    NOK("Norway Krone"),
    NZD("New Zealand Dollar"),
    PLN("Poland Zloty"),
    RUB("Russia Ruble"),
    SEK("Sweden Krona"),
    SLL("Sierra Leone Leone"),
    THB("Thailand Baht"),
    TRY("Turkey Lira"),
    TWD("Taiwan New Dollar"),
    USD("United States Dollar"),
}